# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "test-zola"
compatibility_date = "2025-08-22"
main = "cf_worker/index.ts"

[assets]
# needed for the worker to access the asset
binding = "ASSETS"
# The path to the directory containing the `index.html` file to be served at `/`
directory = "./public"
run_worker_first = [ "/*" ]

[observability]
enabled = true

[build]
command = './cf-build.sh'


[vars]
# CFP_PASSWORD should be set as a secret using 'wrangler secret put CFP_PASSWORD'
# CFP_PASSWORD = "mySecret"
